In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

### 1.문제정의(목적) - SVM으로 iris 데이터를 분류 해보자

### 2. 데이터 수집

In [34]:
#아이리스 데이터 불러오기
df = load_iris()
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [35]:
#독립변수, 종속변수 설정
x = df.data
y = df.target

In [36]:
#데이터 프레임화
x = pd.DataFrame(x, columns=df.feature_names)
y = pd.DataFrame(y, columns=['species'])

### 3. 데이터 전처리
 - 스케일링
 - 레이블 인코딩

In [37]:
#스케일링
transformer = MinMaxScaler()
transformer.fit(x)

MinMaxScaler()

In [38]:
x_data = transformer.transform(x)

In [39]:
x_data

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [40]:
# 레이블 인코딩
le = LabelEncoder()
le.fit(y)

c:\Users\user\anaconda\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [41]:
print(le.classes_)

[0 1 2]


In [42]:
y_data = le.transform(y)

c:\Users\user\anaconda\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [43]:
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [44]:
# train, test split
x_train, x_test, y_train, y_test = train_test_split(x_data,y_data, random_state = 0)

### 4. EDA(탐색적 데이터 분석) - 클래스별 비율, 시각화

### 5. 모델 선택

In [45]:
model = SVC(kernel='rbf', C=1.0, gamma='auto', probability=True) #가우시안 커널


### 6. 모델 학습

In [46]:
model.fit(x_train, y_train)

SVC(gamma='auto', probability=True)

### 7. 모델 평가

In [47]:
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.9464285714285714
0.9736842105263158


In [48]:
labels = ['setosa', 'versicolor', 'verginica']

#### 새로운 데이터 예측

In [49]:
new_test = [[6.0, 3.8, 1.5 , 0.2]]
new_test = pd.DataFrame(new_test, columns=['Sepal length', 'Sepal width', 'Petal length', 'Petal width'])

In [50]:
new_test = transformer.transform(new_test)

c:\Users\user\anaconda\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Petal length
- Petal width
- Sepal length
- Sepal width
Feature names seen at fit time, yet now missing:
- petal length (cm)
- petal width (cm)
- sepal length (cm)
- sepal width (cm)

  warnings.warn(message, FutureWarning)


In [51]:
y_predict = model.predict(new_test)

In [52]:
label = labels[y_predict[0]]

In [54]:
print(label)

setosa
