# 데이터 전처리

## 1. 결측치 처리
    - 제거
    - 채우기

In [126]:
import pandas as pd
import numpy as np

In [127]:
d= {'score1':[100,90, np.nan, 95], 
    'score2':[30,np.nan,45,56],
    'score3':[52,40,80,98],
    'score4':[np.nan,np.nan,np.nan,65] }

In [128]:
df = pd.DataFrame(d)
df.head()

score1  score2  score3  score4
0   100.0    30.0      52     NaN
1    90.0     NaN      40     NaN
2     NaN    45.0      80     NaN
3    95.0    56.0      98    65.0

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   score1  3 non-null      float64
 1   score2  3 non-null      float64
 2   score3  4 non-null      int64  
 3   score4  1 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes


In [130]:
# null 값 확인
df.isnull().sum()

score1    1
score2    1
score3    0
score4    3
dtype: int64

In [131]:
df[df.score1.isnull()]

score1  score2  score3  score4
2     NaN    45.0      80     NaN

#### 행을 기준으로 삭제
 - axis = 0

In [132]:
df.dropna()

score1  score2  score3  score4
3    95.0    56.0      98    65.0

In [133]:
# how='any': 결측치가 있는 행 전부를 지우겠다.
df.dropna(axis=0 , how='any')

score1  score2  score3  score4
3    95.0    56.0      98    65.0

#### 열을 기준으로 삭제
     - axis = 1

In [134]:
df.dropna(axis=1)

score3
0      52
1      40
2      80
3      98

#### 행의 전체값이 결측치인 행을 삭제

In [135]:
d2= {'score1':[100, np.nan, np.nan, 95],
     'score2':[np.nan, np.nan,np.nan,np.nan ],
     'score3':[52, np.nan, 80, 98],
     'score4':[np.nan, np.nan,np.nan, 65]}

In [136]:
df2= pd.DataFrame(d2)
df2

score1  score2  score3  score4
0   100.0     NaN    52.0     NaN
1     NaN     NaN     NaN     NaN
2     NaN     NaN    80.0     NaN
3    95.0     NaN    98.0    65.0

In [137]:
#how='all' 모든 값이 Null 일 경우에만 삭제
df2.dropna(how='all')

score1  score2  score3  score4
0   100.0     NaN    52.0     NaN
2     NaN     NaN    80.0     NaN
3    95.0     NaN    98.0    65.0

#### 임계치 설정해서 제거

In [138]:
# thresh = n : 직접 몇개 지정
df2.dropna(thresh=2)

score1  score2  score3  score4
0   100.0     NaN    52.0     NaN
3    95.0     NaN    98.0    65.0

##### 적당한 임계치는 분석가가 판단해서 잘 설정해야함

#### 특정 열 안에서만 삭제

In [139]:
df.dropna(subset=['score2', 'score4'])

score1  score2  score3  score4
3    95.0    56.0      98    65.0

## 결측치 채우기

In [140]:
#특정한 단일 값으로 채우고 싶을때 .fillna()
df.fillna(0)

score1  score2  score3  score4
0   100.0    30.0      52     0.0
1    90.0     0.0      40     0.0
2     0.0    45.0      80     0.0
3    95.0    56.0      98    65.0

#### 결측치 바로 이전의 값으로 채우기
 - 각 nan 값들이 이전의 값들로 채워짐, 앞의 행이 nan값이면 채워지지 않고 그대로 nan값을 가지게 됨

In [141]:
df.fillna(method='pad')

score1  score2  score3  score4
0   100.0    30.0      52     NaN
1    90.0    30.0      40     NaN
2    90.0    45.0      80     NaN
3    95.0    56.0      98    65.0

#### 결측치 바로 뒤의 값으로 채우기

In [142]:
df.fillna(method='bfill')

score1  score2  score3  score4
0   100.0    30.0      52    65.0
1    90.0    45.0      40    65.0
2    95.0    45.0      80    65.0
3    95.0    56.0      98    65.0

#### 결측치를 각 열의 평균값으로 채우기

In [143]:
df.fillna(df.mean())

score1     score2  score3  score4
0   100.0  30.000000      52    65.0
1    90.0  43.666667      40    65.0
2    95.0  45.000000      80    65.0
3    95.0  56.000000      98    65.0

#### 결측치를 각 열의 중간값, 최소값, 최대값으로 채우기

In [144]:
#최대값
df.fillna(df.max())

score1  score2  score3  score4
0   100.0    30.0      52    65.0
1    90.0    56.0      40    65.0
2   100.0    45.0      80    65.0
3    95.0    56.0      98    65.0

In [145]:
#최소값
df.fillna(df.min())

score1  score2  score3  score4
0   100.0    30.0      52    65.0
1    90.0    30.0      40    65.0
2    90.0    45.0      80    65.0
3    95.0    56.0      98    65.0

In [146]:
#중간값
df.fillna(df.median())

score1  score2  score3  score4
0   100.0    30.0      52    65.0
1    90.0    45.0      40    65.0
2    95.0    45.0      80    65.0
3    95.0    56.0      98    65.0

#### replace()함수로 결측치 채우기

In [147]:
df.replace(to_replace=np.nan, value=0)

score1  score2  score3  score4
0   100.0    30.0      52     0.0
1    90.0     0.0      40     0.0
2     0.0    45.0      80     0.0
3    95.0    56.0      98    65.0

- 지정한 값으로 결측치들이 모두 채워지게 됨(fillna와 동일)
- replace 함수는 nan 값 대신 특정한 문자를 다른 문자로 바꾸고 싶을때 사용 가능

#### interploate() 로 결측치 채우기

In [148]:
# 앞 뒤행의 중간값으로 채워준다...
df.interpolate(method='linear', limit_direction='forward')

score1  score2  score3  score4
0   100.0    30.0      52     NaN
1    90.0    37.5      40     NaN
2    92.5    45.0      80     NaN
3    95.0    56.0      98    65.0

In [149]:
# fillna(method='pad')와 같은 방법
df.interpolate(method='pad', limit=2)

score1  score2  score3  score4
0   100.0    30.0      52     NaN
1    90.0    30.0      40     NaN
2    90.0    45.0      80     NaN
3    95.0    56.0      98    65.0

## 2. 범주형 데이터

### 원핫인코딩으로 변경
 - 모든 데이터를 0과 1로 변환 하는것
 - 컴퓨터는 모든 데이터를 이진법으로 처리하기 때문에 레이블인코딩보다는 원핫인코딩을 사용한다.

In [150]:
df = pd.read_csv('./mushrooms.csv')
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [151]:
one = pd.get_dummies(df)

In [152]:
#각 컬럼의 값들을 각각 새로운 열추가해줘서 0, 1로 치환해줌
one

class_e  class_p  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  \
0           0        1            0            0            0            0   
1           1        0            0            0            0            0   
2           1        0            1            0            0            0   
3           0        1            0            0            0            0   
4           1        0            0            0            0            0   
...       ...      ...          ...          ...          ...          ...   
8119        1        0            0            0            0            1   
8120        1        0            0            0            0            0   
8121        1        0            0            0            1            0   
8122        0        1            0            0            0            1   
8123        1        0            0            0            0            0   

      cap-shape_s  cap-shape_x  cap-surface_f  cap-surface_g  ...  \
0               0            1              0              0  ...   
1               0            1              0              0  ...   
2               0            0              0              0  ...   
3               0            1              0              0  ...   
4               0            1              0              0  ...   
...           ...          ...            ...            ...  ...   
8119            0            0              0              0  ...   
8120            0            1              0              0  ...   
8121            0            0              0              0  ...   
8122            0            0              0              0  ...   
8123            0            1              0              0  ...   

      population_s  population_v  population_y  habitat_d  habitat_g  \
0                1             0             0          0          0   
1                0             0             0          0          1   
2                0             0             0          0          0   
3                1             0             0          0          0   
4                0             0             0          0          1   
...            ...           ...           ...        ...        ...   
8119             0             0             0          0          0   
8120             0             1             0          0          0   
8121             0             0             0          0          0   
8122             0             1             0          0          0   
8123             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 119 columns]

 - .get_dummies()의 문제점
    - train 데이터에만 있고 test데이터에는 없는 카테고리를 원핫인코딩된 칼럼으로 바꿔주지 못함

- sklearn OneHotEncoder 사용

In [153]:
x = df.iloc[:,1:]
y = df['class']

In [154]:
from sklearn.preprocessing import OneHotEncoder

In [155]:
one = OneHotEncoder(sparse=False)
one.fit(x[['cap-shape']])

OneHotEncoder(sparse=False)

In [156]:
train_cap = one.transform(x[['cap-shape']])

In [157]:
print(train_cap)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [158]:
one.categories_

[array(['b', 'c', 'f', 'k', 's', 'x'], dtype=object)]

In [159]:
o = pd.DataFrame(train_cap, columns=['cap-shape_'
                                     +col for col in one.categories_[0]])

In [160]:
one_x = pd.concat([x.drop(columns=['cap-shape']), o], axis=1)

In [161]:
one_x

cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0              s         n       t    p               f            c   
1              s         y       t    a               f            c   
2              s         w       t    l               f            c   
3              y         w       t    p               f            c   
4              s         g       f    n               f            w   
...          ...       ...     ...  ...             ...          ...   
8119           s         n       f    n               a            c   
8120           s         n       f    n               a            c   
8121           s         n       f    n               a            c   
8122           y         n       f    y               f            c   
8123           s         n       f    n               a            c   

     gill-size gill-color stalk-shape stalk-root  ... ring-type  \
0            n          k           e          e  ...         p   
1            b          k           e          c  ...         p   
2            b          n           e          c  ...         p   
3            n          n           e          e  ...         p   
4            b          k           t          e  ...         e   
...        ...        ...         ...        ...  ...       ...   
8119         b          y           e          ?  ...         p   
8120         b          y           e          ?  ...         p   
8121         b          n           e          ?  ...         p   
8122         n          b           t          ?  ...         e   
8123         b          y           e          ?  ...         p   

     spore-print-color population habitat cap-shape_b cap-shape_c cap-shape_f  \
0                    k          s       u         0.0         0.0         0.0   
1                    n          n       g         0.0         0.0         0.0   
2                    n          n       m         1.0         0.0         0.0   
3                    k          s       u         0.0         0.0         0.0   
4                    n          a       g         0.0         0.0         0.0   
...                ...        ...     ...         ...         ...         ...   
8119                 b          c       l         0.0         0.0         0.0   
8120                 b          v       l         0.0         0.0         0.0   
8121                 b          c       l         0.0         0.0         1.0   
8122                 w          v       l         0.0         0.0         0.0   
8123                 o          c       l         0.0         0.0         0.0   

     cap-shape_k cap-shape_s cap-shape_x  
0            0.0         0.0         1.0  
1            0.0         0.0         1.0  
2            0.0         0.0         0.0  
3            0.0         0.0         1.0  
4            0.0         0.0         1.0  
...          ...         ...         ...  
8119         1.0         0.0         0.0  
8120         0.0         0.0         1.0  
8121         0.0         0.0         0.0  
8122         1.0         0.0         0.0  
8123         0.0         0.0         1.0  

[8124 rows x 27 columns]

In [162]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(one_x, y, random_state=0)

In [163]:
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))

6093
6093
2031
2031


### 범주 특성을 레이블 인코딩으로 변환
- 숫자의 크고 작음에 대한 특성이 작용함
- 회귀와 같이 연속된 실수를 다루는 알고리즘에서 레이블인코딩을 사용하면 잘못된 결과값이 나올 수 있음

In [164]:
one_x['cap-surface'].unique()

array(['s', 'y', 'f', 'g'], dtype=object)

In [165]:
# cap-surface의 유니크한 카테고리 데이터 개수 확인
one_x['cap-surface'].value_counts()

y    3244
s    2556
f    2320
g       4
Name: cap-surface, dtype: int64

In [166]:
# 인코딩 전
one_x['cap-surface']

0       s
1       s
2       s
3       y
4       s
       ..
8119    s
8120    s
8121    s
8122    y
8123    s
Name: cap-surface, Length: 8124, dtype: object

In [167]:
#인코딩 후 - map 사용
one_x['cap-surface'] = one_x['cap-surface'].map({'y':0,'s':1,'f':2,'g':3})

In [169]:
one_x['cap-surface'].value_counts()

0    3244
1    2556
2    2320
3       4
Name: cap-surface, dtype: int64

In [170]:
from sklearn.preprocessing import LabelEncoder

In [171]:
encoder = LabelEncoder()
encoder.fit(one_x['cap-color'])#학습

LabelEncoder()

In [172]:
one_x['cap-color'] = encoder.transform(one_x['cap-color'])

In [175]:
one_x['cap-color'].value_counts()

4    2284
3    1840
2    1500
9    1072
8    1040
0     168
5     144
1      44
7      16
6      16
Name: cap-color, dtype: int64