In [1]:
import module_test as mt

In [2]:
mt.add(10,20), mt.minus(10,20), mt.multiple(10,20), mt.divided(10,20)

(30, -10, 200, 0.5)

# 모듈
 - numpy = 고성능 과학계산을 위한 데이터 분석 라이브러리
 - pandas = 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리 
 - matplotlib = 2D 그래프로 시각화가 가능한 라이브러리

In [3]:
import numpy as np

In [4]:
# 1차원 ndarry
list1  = [1,2,3,4,5,6]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# 2차원 ndarry
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [7]:
# 배열의 크기 확인하기
arr1.shape, arr2.shape

((7,), (2, 5))