In [27]:
import module_test as mt

In [28]:
mt.add(10,20), mt.minus(10,20), mt.multiple(10,20), mt.divided(10,20)

(30, -10, 200, 0.5)

# 모듈
 - numpy = 고성능 과학계산을 위한 데이터 분석 라이브러리
 - pandas = 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리 
 - matplotlib = 2D 그래프로 시각화가 가능한 라이브러리

In [29]:
import numpy as np

In [30]:
# 1차원 ndarry
list1  = [1,2,3,4,5,6]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6])

In [31]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
# 2차원 ndarry
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [33]:
# 3차원 ndarray
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[4,5,6,7,8],[2,4,6,8,0]]])
arr3

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[4, 5, 6, 7, 8],
        [2, 4, 6, 8, 0]]])

In [34]:
# 배열의 크기 확인하기
arr1.shape, arr2.shape, arr3.shape

((7,), (2, 5), (2, 2, 5))

In [35]:
# 전체 요소의 개수 확인하기
print(arr1)
print(arr1.size)
print(arr2)
print(arr2.size)

print(arr3)
print(arr3.size)

[1 2 3 4 5 6 7]
7
[[1 2 3 4 5]
 [6 7 8 9 0]]
10
[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[4 5 6 7 8]
  [2 4 6 8 0]]]
20


In [36]:
# 배열의 타입 확인
print(arr1)
print(arr1.dtype)
print(arr2)
print(arr2.dtype)
print(arr3)
print(arr3.dtype)


[1 2 3 4 5 6 7]
int32
[[1 2 3 4 5]
 [6 7 8 9 0]]
int32
[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[4 5 6 7 8]
  [2 4 6 8 0]]]
int32


In [37]:
# 배열의 차원 확인
print(arr1)
print(arr1.ndim)
print(arr2)
print(arr2.ndim)
print(arr3)
print(arr3.ndim)

[1 2 3 4 5 6 7]
1
[[1 2 3 4 5]
 [6 7 8 9 0]]
2
[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[4 5 6 7 8]
  [2 4 6 8 0]]]
3


## Array Creation

In [38]:
# 특정한 값으로 배열 생성하기
## 모든 값 0으로 초기화
arr_zeros = np.zeros((3,5))
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
## 모든 값 1로 초기화
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
arr_full = np.full((5,5),7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [44]:
arr50 = []
for i in range(1,51):
    arr50.append(i)

In [45]:
arr5 = np.array(arr50)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [46]:
arr6 = np.arange(1,51)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [50]:
arr7 = np.arange(1,51,10) # 1부터 , 51미만 , 10의 단위로
arr7

array([ 1, 11, 21, 31, 41])

In [61]:
#랜덤으로 넣어줄때
arr_rd = np.random.rand(2,3)
arr_rd

array([[0.33560914, 0.35460778, 0.36389973],
       [0.69052813, 0.78025424, 0.1768105 ]])

In [65]:
#랜덤 값 배열 생성하기
arr = np.random.randint(2,10)
arr

6

In [68]:
arr= np.random.randint(2,10,size=(2,3))
arr

array([[6, 8, 7],
       [8, 5, 9]])

In [70]:
# 타입 지정하여 배열 생성하기
arr_type = np.array([1.2,2.3,3.4,5.6], dtype = np.int64)
arr_type

array([1, 2, 3, 5], dtype=int64)

In [75]:
# 타입 변경하기
arr_type = arr_type.astype("float64")
arr_type, arr_type.dtype

(array([1., 2., 3., 5.]), dtype('float64'))

### Array Operation

In [79]:
#array 연산 (요소별 연산)
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [80]:
arr + arr

array([2, 4, 6, 8])

In [81]:
arr*arr

array([ 1,  4,  9, 16])

In [82]:
#array 연산 1차원
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

In [83]:
arr_a + arr_b

array([5, 7, 9])

In [85]:
# array 연산 2차원
arr_2a = np.array([[1,2,3,4],[5,6,7,8]])
arr_2b = np.array([[2,4,6,8],[1,3,5,7]])
print(arr_2a + arr_2b)
print(arr_2a - arr_2b)


[[ 3  6  9 12]
 [ 6  9 12 15]]
[[-1 -2 -3 -4]
 [ 4  3  2  1]]


In [86]:
arr_2a + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
arr_2b * 2

array([[ 4,  8, 12, 16],
       [ 2,  6, 10, 14]])

## indexing & slicing
 - 인덱싱 = 무언가를 '가르킨다'는 의미
 - 슬라이싱 = 무언가를 '잘라낸다'는 의미

In [88]:
# array 인덱싱 (1차원배열)
arr_1 = np.array([0,1,2,3,4,5]) 

In [89]:
arr_1[2]

2

In [90]:
## array 인덱싱 (2차원배열)
arr_2 = np.array([[1,2,3],[4,5,6]])

In [98]:
arr_2[0],
arr_2[0,0],
arr_2[0][0]

1

In [102]:
print("1. ", arr_2[1,0])
print("2. ", arr_2[1,2])
print("3. " , arr_2[1])

1.  4
2.  6
3.  [4 5 6]


In [104]:
# 1차원 array 슬라이싱
arr1 = np.arange(10)
arr1[3:8]

array([3, 4, 5, 6, 7])

In [106]:
arr1[3:8] = 12
arr1

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [108]:
# 2차원 배열 만들기 (reshape 활용)
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [109]:
arr2[:2,:] # 0행부터 1행까지 전체 열(세로) 출력

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [116]:
# 전체 행의 1열만 출력
arr2[:,0]

array([ 0, 10, 20, 30, 40])

In [121]:
# 0 행 부터 3행까지 0열부터 4열까지 출력
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [124]:
arr2[2,1]

21

In [125]:
print(arr2[4,8])
print(arr2[2,9])
print(arr2[1,2])

48
29
12


## Boolean 색인
 - 배열 안에서 조건을 충족하는 True 인 값들만 추출해주는 인덱싱 방법

In [126]:
score = np.array([80,75,55,96,30])
score

array([80, 75, 55, 96, 30])

In [127]:
score >= 80

array([ True, False, False,  True, False])

In [129]:
score[score>=80]

array([80, 96])

In [130]:
name = np.array(["영화","동원","성우","수민"])
name

array(['영화', '동원', '성우', '수민'], dtype='<U2')

In [131]:
bol = np.array([False,True,False,True])
bol

array([False,  True, False,  True])

In [132]:
name[bol]

array(['동원', '수민'], dtype='<U2')