In [3]:
mid_score = [10,20,30]
final_score = [70,80,90]

In [5]:
total = mid_score + final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [6]:
import numpy as np

In [8]:
ms = np.array(mid_score)
fs = np.array(final_score)

In [10]:
total = ms + fs 
print(total)

[ 80 100 120]


In [11]:
print("시험 성적의 합계: ",total)

시험 성적의 합계:  [ 80 100 120]


In [14]:
print("시험 성적의 합계: ",total/2)

시험 성적의 합계:  [40. 50. 60.]


In [24]:
array_a = np.array([0,1,2,3,4,5,6,7,8,9])
array_a
# array_a = np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array_b = np.arange(0,10)
print(array_b)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
array_c = np.arange(0,10,2)
print(array_c)

[0 2 4 6 8]


In [21]:
print(array_c.shape)
print(array_c.ndim)
print(array_c.dtype)
print(array_c.size)

(5,)
1
int32
5


In [25]:
array_c.itemsize # 배열 내의 원소 크기를 byte 단위로 알려줌

4

In [27]:
salary = np.array([220,250,230])
salary = salary + 100
salary

array([320, 350, 330])

In [28]:
salary = np.array([220,250,230])
salary = salary *2 
salary

array([440, 500, 460])

In [29]:
players = [[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [30]:
np_players = np.array(players)
print(np_players) 

[[170.   76.4]
 [183.   86.2]
 [171.   73.5]
 [176.   80.1]]


In [37]:
print("몸무게가 80 이상인 선수의 정보",np_players[np_players[:,1]>=80.0])

몸무게가 80 이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [59]:
print("키가 180 이상인 선수의 정보",np_players[np_players[:,0]>=180.0])

키가 180 이상인 선수의 정보 [[183.   86.2]]


In [60]:
revenu_in_yen = [3.5,5.2,4.0,8,10,2.5,3,10,5.5,11,13,2.0,4,5,6,5,4,4,3,2,0,10,3,4,5,6,7,8,1,3]

In [65]:
np_rev_yen = np.array(revenu_in_yen)
np_rev_yen.size

30

In [68]:
won_array = (np_rev_yen*9.7)*10000
won_array

array([ 339500.,  504400.,  388000.,  776000.,  970000.,  242500.,
        291000.,  970000.,  533500., 1067000., 1261000.,  194000.,
        388000.,  485000.,  582000.,  485000.,  388000.,  388000.,
        291000.,  194000.,       0.,  970000.,  291000.,  388000.,
        485000.,  582000.,  679000.,  776000.,   97000.,  291000.])

In [69]:
dol_array = (np_rev_yen*0.0070)*10000
dol_array

array([245., 364., 280., 560., 700., 175., 210., 700., 385., 770., 910.,
       140., 280., 350., 420., 350., 280., 280., 210., 140.,   0., 700.,
       210., 280., 350., 420., 490., 560.,  70., 210.])

In [71]:
total = won_array + (dol_array*1391.22)
total

array([ 680348.9 , 1010804.08,  777541.6 , 1555083.2 , 1943854.  ,
        485963.5 ,  583156.2 , 1943854.  , 1069119.7 , 2138239.4 ,
       2527010.2 ,  388770.8 ,  777541.6 ,  971927.  , 1166312.4 ,
        971927.  ,  777541.6 ,  777541.6 ,  583156.2 ,  388770.8 ,
             0.  , 1943854.  ,  583156.2 ,  777541.6 ,  971927.  ,
       1166312.4 , 1360697.8 , 1555083.2 ,  194385.4 ,  583156.2 ])

In [74]:
tw = total.astype("int64")

In [75]:
tw[tw<=500000]

array([485963, 388770, 388770,      0, 194385], dtype=int64)