In [2]:
import numpy as np

In [3]:
ar0 = np.zeros(10)
ar0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ar0[4] = 1 
ar0

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
c = np.random.randint(0, 10, size=(3,3,3))
c

array([[[0, 7, 6],
        [8, 6, 0],
        [3, 4, 7]],

       [[5, 8, 6],
        [5, 1, 6],
        [0, 9, 5]],

       [[9, 9, 4],
        [0, 7, 1],
        [6, 1, 4]]])

In [8]:
d= np.random.random(30)
d

array([0.45366111, 0.37857658, 0.77354527, 0.4890247 , 0.10074152,
       0.77795351, 0.26991341, 0.68585845, 0.63800302, 0.30032537,
       0.94050826, 0.54863189, 0.11520217, 0.43770037, 0.1660343 ,
       0.71981518, 0.05020963, 0.21080159, 0.69534444, 0.53874598,
       0.28680547, 0.18277503, 0.83174148, 0.1798703 , 0.15355356,
       0.83402428, 0.25099807, 0.84269349, 0.35667958, 0.06050386])

In [9]:
np.mean(d)

0.4423413944828826

In [10]:
arr = np.arange(2,51,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [11]:
arr1 = np.zeros((4,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr2 = np.ones((10,10))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
arr3 = np.full((7,4),7)
arr3

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# 1부터 100까지 원소중 3의 배수를 원소로 갖ㄴ는 넘파이 배열 생성
arr_4 = np.arange(3,101,3)
arr_4

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
#만들어진 3의 배수를 원소로 갖는 넘파이 배열의 개수를 구하고 , reshape 함수를 이용하여
#2차원 배열을 생성하시오.
#생성된 2차원 배열의 크기를 구하시오

In [15]:
print(arr_4.size)

33


In [20]:
arr_5 = arr_4.reshape(11,3)
arr_5

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54],
       [57, 60, 63],
       [66, 69, 72],
       [75, 78, 81],
       [84, 87, 90],
       [93, 96, 99]])

In [21]:
arr_5.shape

(11, 3)

In [22]:
import random

### 연습
### 1. 0~1 사이의 값을 랜덤하게 가지는 6*4 배열생성
### 2. 1~ 100 사이의 값을 랜덤하게 가지는 5*5 배열생성
### 3. astype 을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸시오.

In [27]:
arr_r1 = np.random.rand(6,4)
arr_r1

array([[0.97831889, 0.44616633, 0.60936354, 0.79577921],
       [0.59812994, 0.9198783 , 0.63543602, 0.74646142],
       [0.85952892, 0.05933825, 0.41178172, 0.73114349],
       [0.73775736, 0.1443331 , 0.58316474, 0.4876072 ],
       [0.15832309, 0.09519536, 0.49612031, 0.40525397],
       [0.39890289, 0.93939127, 0.92347113, 0.59614716]])

In [29]:
arr_r2 = np.random.randint(1,101,(5,5))
arr_r2

array([[34, 51, 97, 10, 76],
       [65, 91, 56, 27,  9],
       [31, 53,  7, 55, 11],
       [88, 28, 39, 64,  9],
       [51, 27, 66, 38, 42]])

In [30]:
arr_float = arr_r2.astype("float64")
arr_float

array([[34., 51., 97., 10., 76.],
       [65., 91., 56., 27.,  9.],
       [31., 53.,  7., 55., 11.],
       [88., 28., 39., 64.,  9.],
       [51., 27., 66., 38., 42.]])

In [31]:
# 주어진 배열에서 3,4,8,9 원소만 가져오기
# 주어진 배열에서 6,7,8 원소만 가져오기
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
x[:,3:]


array([[3, 4],
       [8, 9]])

In [34]:
x[1,1:4]

array([6, 7, 8])

In [35]:
y=np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### 3,8,13 원소 가져오기
### 5,6,7,8,9 원소 가져오기
### 1,2,3,6,7,8 원소 가져오기

In [36]:
y[:,3]

array([ 3,  8, 13])

In [37]:
y[1,:]

array([5, 6, 7, 8, 9])

In [39]:
y[:2,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [40]:
arr2d= np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#arr2d에서 5보다 작거나 같은 값만 추출하시오.

In [ ]:
arr2d[:2,]