In [1]:
import numpy as np

In [2]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
len(temp)

31

In [3]:
# 값 이 25 이상인 것의 개수, 평균
print(temp[temp> 25.0].size)
print(np.mean(temp[temp > 25]))

21
26.857142857142858


In [4]:
# 정렬
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [5]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [6]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [7]:
np.sort(arr2d, axis=1) # 열 정렬

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [8]:
np.sort(arr2d, axis=0) # 행 정렬

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [9]:
y = np.random.randint (100,size=(3,5))
print(y.mean(), y.sum(), y.max(), y.min(), y.var(), np.median(y), y.std())
# 평균, 합계, 최대, 최소, 분산 np.var(), 중앙값 np.median(), 표준 편차 np.std()

52.86666666666667 793 94 14 665.3155555555554 55.0 25.79371155059999


In [10]:
data = np.loadtxt("height_weight.txt", delimiter = ",") # delimiter : 구분기호 , txt 데이터 불러오기
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [11]:
data.shape

(2, 10)

In [12]:
height_cm = data[0] # 키 데이터
weight_kg = data[1] # 몸무게 데이터


In [13]:
height_m = height_cm / 100


In [14]:
BMI = weight_kg/(height_m**2)
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [15]:
data = np.loadtxt("ratings.txt",delimiter = "::", dtype="int")
data
#[user id, x, 평점, x]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [16]:
print(data.shape, data.ndim, data.size)

(1000209, 4) 2 4000836


In [17]:
# 유저 id가 1 인 데이터
print(data[data[:,0] == 1])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1

In [18]:
# 유저 평점의 평균
user_id = data[:,0]
ratings = data[:,2]
ratings.mean()

3.581564453029317

In [19]:
#유저 id 1인 유저의 평점 평균
data[data[:,0] == 1,2].mean()

4.188679245283019