In [1]:
import numpy as np

In [4]:
ar0 = np.zeros(10)
ar0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
ar0[4] = 1 
ar0

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
c = np.random.randint(0, 10, size=(3,3,3))
c

array([[[7, 2, 5],
        [8, 6, 5],
        [6, 8, 8]],

       [[0, 0, 4],
        [9, 4, 2],
        [2, 2, 5]],

       [[0, 6, 6],
        [2, 6, 7],
        [6, 7, 6]]])

In [30]:
d= np.random.random(30)
d

array([0.33085832, 0.17320874, 0.39260183, 0.8571654 , 0.94442266,
       0.993385  , 0.92074133, 0.10851865, 0.1052671 , 0.93451977,
       0.85888107, 0.09116724, 0.29388429, 0.58584189, 0.99082542,
       0.26110729, 0.23389535, 0.20771314, 0.31354006, 0.81160745,
       0.19418569, 0.85584375, 0.68227336, 0.29736305, 0.90699585,
       0.18396061, 0.52368041, 0.95809024, 0.52476793, 0.9831534 ])

In [31]:
np.mean(d)

0.5506488757185373